require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GazooiesController do

  # This should return the minimal set of attributes required to create a valid
  # Gazooy. As you add validations to Gazooy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GazooiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gazooies as @gazooies" do
      gazooy = Gazooy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gazooies).should eq([gazooy])
    end
  end

  describe "GET show" do
    it "assigns the requested gazooy as @gazooy" do
      gazooy = Gazooy.create! valid_attributes
      get :show, {:id => gazooy.to_param}, valid_session
      assigns(:gazooy).should eq(gazooy)
    end
  end

  describe "GET new" do
    it "assigns a new gazooy as @gazooy" do
      get :new, {}, valid_session
      assigns(:gazooy).should be_a_new(Gazooy)
    end
  end

  describe "GET edit" do
    it "assigns the requested gazooy as @gazooy" do
      gazooy = Gazooy.create! valid_attributes
      get :edit, {:id => gazooy.to_param}, valid_session
      assigns(:gazooy).should eq(gazooy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gazooy" do
        expect {
          post :create, {:gazooy => valid_attributes}, valid_session
        }.to change(Gazooy, :count).by(1)
      end

      it "assigns a newly created gazooy as @gazooy" do
        post :create, {:gazooy => valid_attributes}, valid_session
        assigns(:gazooy).should be_a(Gazooy)
        assigns(:gazooy).should be_persisted
      end

      it "redirects to the created gazooy" do
        post :create, {:gazooy => valid_attributes}, valid_session
        response.should redirect_to(Gazooy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gazooy as @gazooy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gazooy.any_instance.stub(:save).and_return(false)
        post :create, {:gazooy => { "user_id" => "invalid value" }}, valid_session
        assigns(:gazooy).should be_a_new(Gazooy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gazooy.any_instance.stub(:save).and_return(false)
        post :create, {:gazooy => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gazooy" do
        gazooy = Gazooy.create! valid_attributes
        # Assuming there are no other gazooies in the database, this
        # specifies that the Gazooy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gazooy.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => gazooy.to_param, :gazooy => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested gazooy as @gazooy" do
        gazooy = Gazooy.create! valid_attributes
        put :update, {:id => gazooy.to_param, :gazooy => valid_attributes}, valid_session
        assigns(:gazooy).should eq(gazooy)
      end

      it "redirects to the gazooy" do
        gazooy = Gazooy.create! valid_attributes
        put :update, {:id => gazooy.to_param, :gazooy => valid_attributes}, valid_session
        response.should redirect_to(gazooy)
      end
    end

    describe "with invalid params" do
      it "assigns the gazooy as @gazooy" do
        gazooy = Gazooy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gazooy.any_instance.stub(:save).and_return(false)
        put :update, {:id => gazooy.to_param, :gazooy => { "user_id" => "invalid value" }}, valid_session
        assigns(:gazooy).should eq(gazooy)
      end

      it "re-renders the 'edit' template" do
        gazooy = Gazooy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gazooy.any_instance.stub(:save).and_return(false)
        put :update, {:id => gazooy.to_param, :gazooy => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gazooy" do
      gazooy = Gazooy.create! valid_attributes
      expect {
        delete :destroy, {:id => gazooy.to_param}, valid_session
      }.to change(Gazooy, :count).by(-1)
    end

    it "redirects to the gazooies list" do
      gazooy = Gazooy.create! valid_attributes
      delete :destroy, {:id => gazooy.to_param}, valid_session
      response.should redirect_to(gazooies_url)
    end
  end

end
